export const ISRESULT = "ISRESULT";
//Test
export const GET_DATA_TEST_TEST = "GET_DATA_TEST_TEST";
export const GET_DATA_TEST123_TEST = "GET_DATA_TEST123_TEST";
export const GET_DATA_TEST_TEST_SUCCEEDED = "GET_DATA_TEST_TEST_SUCCEEDED";
export const REQUERT_TEST_TEST_FAILED = "REQUERT_TEST_TEST_FAILED";
export const SET_DATA_TEST_TEST = "SET_DATA_TEST_TEST";
export const GET_DATA_TEST123_TEST_SUCCEEDED =
  "GET_DATA_TEST123_TEST_SUCCEEDED";
export const REQUERT_TEST123_TEST_FAILED = "REQUERT_TEST123_TEST_FAILED";
export const SET_DATA_TEST123_TEST = "SET_DATA_TEST123_TEST";
//IndexHygen
